import { describe, test, expect } from 'vitest'

import funcQ1 from './code-q1.mjs'
import funcQ2 from './code-q2.mjs'

describe('Day 8', () => {
  test('Question 1', () => {
    const input = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`
    expect(funcQ1(input)).toEqual(14)
  })
  test('Question 1 (simple input)', () => {
    const input = `
..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........`
    expect(funcQ1(input)).toEqual(2)
  })
  test('Question 2', () => {
    const input = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`
    expect(funcQ2(input)).toEqual(34)
  })
  test('Question 2 (simple input)', () => {
    const input = `
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`
    expect(funcQ2(input)).toEqual(9)
  })
  test('Question 2 (simple input 2)', () => {
    const input = `
..T.T.....
..........
..........
..........
..........
..........
..........
..........
..........
..........`
    expect(funcQ2(input)).toEqual(10)
  })
})
